### ISSUE TITLE
Useless error handling

### ISSUE THREAD

**Issue by rluders** [luksrocha/golang-basic-crud#3]
https://github.com/luksrocha/golang-basic-crud/blob/b306fae99db117b5c46c07552ba572e36b87fea3/internal/application/useCases/houseUseCases/deleteHouseUseCase.go#L18

I saw this a few times at the use cases, at this point your error handling is useless... since you are not handling it here, you are just returning it... So, it means that you could return it like this:

```go
return d.houseRepository.Delete(id)
```

**Comment by luksrocha** [comment]
I'm not sure if I get this one @rluders, The `housePostgresRepository` returns an error if anything fails, the useCase captures that error and sends it to the Handler, and then if the handler catches that error it will do that `response.WriteHeader(http.StatusInternalServerError)`.

**Comment by rluders** [comment]
You are not doing anything with the error here. Unless you plan to convert it to something else, by wrapping the error, logging, or transforming it into another error, there is no need for the `if err != nil` ... you can basically return the response from `d.houseRepository.Delete` directly, which would be or a valid err or nil.

Then the error handling would be handled properly by the handler.
